import ru.simplgroupp.rules.BooleanRuleResult
import ru.simplgroupp.interfaces.CreditCalculatorBeanLocal
import java.util.Map
import ru.simplgroupp.util.CalcUtils
import ru.simplgroupp.workflow.SignalRef
import ru.simplgroupp.transfer.CreditRequest
import ru.simplgroupp.transfer.Credit
import java.util.Date
import ru.simplgroupp.rules.AbstractContext
import ru.simplgroupp.util.DatesUtils;

// если текущий кредит еще не начался (сегодня выходной, начнется в понедельник)
rule "[$RULE_NAME_PREFIX$].1"
when 
    $bResult : BooleanRuleResult();
    $cparams : Map();
    $signalRef : SignalRef(processDefKey == "procCR" && name == "msgProlong");
    $context : AbstractContext();
then
	if ( $context.getCreditRequest().getAcceptedCredit() != null && $context.getCreditRequest().getAcceptedCredit().getCreditDataBeg().after( $context.getCurrentDate() )) {	   
    	$bResult.setResultValue(false);
    	$bResult.addInfo(1,"Ваш текущий кредит ещё не начался");
   	} else {
   		int daysCreditMax = ((Integer) $cparams.get("credit.days.sum.max")).intValue();
   		int numProlongsMax = ((Integer) $cparams.get("credit.prolongs.max")).intValue();
   		int daysCredit = DatesUtils.daysDiff($context.getCredit().getCreditDataEnd(), $context.getCredit().getCreditDataBeg());
   		int numProlongs = ($context.getCredit().getCreditLong()==null)?0:$context.getCredit().getCreditLong().intValue();
   		
   		if (daysCredit >= daysCreditMax) {
    		$bResult.setResultValue(false);
    		$bResult.addInfo(2,"Вы не можете превысить максимальный срок кредита " + String.valueOf(daysCreditMax) + " дней");   		
   		}
   		
   		if (numProlongs >= numProlongsMax) {
    		$bResult.setResultValue(false);
    		$bResult.addInfo(3,"Кредит не может быть продлён более " + String.valueOf(numProlongsMax) + " раз" );   		   		
   		}
   	}
end