import ru.simplgroupp.rules.BooleanRuleResult
import ru.simplgroupp.interfaces.CreditCalculatorBeanLocal
import java.util.Map
import ru.simplgroupp.util.CalcUtils
import ru.simplgroupp.workflow.SignalRef
import ru.simplgroupp.transfer.CreditRequest
import ru.simplgroupp.transfer.Credit
import java.util.Date
import ru.simplgroupp.rules.AbstractContext

rule "[$RULE_NAME_PREFIX$].1"
when 
    $bResult : BooleanRuleResult();
    $cparams : Map();
    $signalRef : SignalRef(processDefKey == "procCR" && name == "msgBadDebt");
    $context : AbstractContext();
then   
    $bResult.setResultValue( $context.getCredit().isOverdue($context.getCurrentDate()));
end