import ru.simplgroupp.rules.BooleanRuleResult
import ru.simplgroupp.interfaces.CreditCalculatorBeanLocal
import java.util.Map
import java.util.Date
import ru.simplgroupp.util.CalcUtils
import ru.simplgroupp.workflow.WorkflowObjectActionDef
import ru.simplgroupp.transfer.CreditRequest
import ru.simplgroupp.rules.AbstractContext

rule "[$RULE_NAME_PREFIX$].1"
when 
    $bResult : BooleanRuleResult();
    $actionDef : WorkflowObjectActionDef(businessObjectClass == "ru.simplgroupp.transfer.CreditRequest" && signalRef == "msgEdit");
    $context : AbstractContext(getCreditRequest() != null);
then  
    if ($context.getCurrentUser().getRoleNameDescription().contains("admin")) {
      $bResult.setResultValue(new Boolean(true));
    } else if ($context.getCurrentUser().getRoleNameDescription().contains("verificator")) { 
      $bResult.setResultValue(new Boolean($context.getCreditRequest().getDateContest() != null&&$context.getCreditRequest().getAcceptedCredit() == null&&($context.getCreditRequest().getStatus().getId()==1||$context.getCreditRequest().getStatus().getId()==5)));
    } else if ($context.getCurrentUser().getRoleNameDescription().contains("callcenter")) {
      $bResult.setResultValue(new Boolean($context.getCreditRequest().getDateContest() != null&&$context.getCreditRequest().getAcceptedCredit() == null&&$context.getCreditRequest().getStatus().getId()==5));
    } else {
      $bResult.setResultValue(new Boolean(false)); 
    }
end

rule "[$RULE_NAME_PREFIX$].2"
when 
    $bResult : BooleanRuleResult();
    $actionDef : WorkflowObjectActionDef(businessObjectClass == "ru.simplgroupp.transfer.CreditRequest" && signalRef == "msgEdit");
    $context : AbstractContext( getCreditRequest() == null );
then   
    $bResult.setResultValue(new Boolean(false));
end
