import ru.simplgroupp.rules.BooleanRuleResult
import ru.simplgroupp.interfaces.CreditCalculatorBeanLocal
import java.util.Map
import ru.simplgroupp.util.CalcUtils
import ru.simplgroupp.workflow.SignalRef

rule "[$RULE_NAME_PREFIX$].1"
when 
    $bResult : BooleanRuleResult();
    $cparams : Map();
    $signalRef : SignalRef(processDefKey == "procCR" && name == "msgReturn");
then   
    $bResult.setResultValue(true);
end