
package ru.simplgroupp.idv;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HSMSWebService1", targetNamespace = "http://experian.com/bureau/hosted/nbsm", wsdlLocation = "https://hs-test.rb-ei.com/HSMSwebservice1.asmx")
public class HSMSWebService1
    extends Service
{

    private final static URL HSMSWEBSERVICE1_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ru.simplgroupp.idv.HSMSWebService1 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ru.simplgroupp.idv.HSMSWebService1 .class.getResource(".");
            url = new URL(baseUrl, "https://hs-test.rb-ei.com/HSMSwebservice1.asmx");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://hs-test.rb-ei.com/HSMSwebservice1.asmx', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HSMSWEBSERVICE1_WSDL_LOCATION = url;
    }

    public HSMSWebService1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HSMSWebService1(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://experian.com/bureau/hosted/nbsm", "HSMSWebService1"));
    }
    
    public HSMSWebService1() {
        super(HSMSWEBSERVICE1_WSDL_LOCATION, new QName("http://experian.com/bureau/hosted/nbsm", "HSMSWebService1"));
    }

    /**
     * 
     * @return
     *     returns HSMSWebService1Soap
     */
    @WebEndpoint(name = "HSMSWebService1Soap")
    public HSMSWebService1Soap getHSMSWebService1Soap() {
        return super.getPort(new QName("http://experian.com/bureau/hosted/nbsm", "HSMSWebService1Soap"), HSMSWebService1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HSMSWebService1Soap
     */
    @WebEndpoint(name = "HSMSWebService1Soap")
    public HSMSWebService1Soap getHSMSWebService1Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://experian.com/bureau/hosted/nbsm", "HSMSWebService1Soap"), HSMSWebService1Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns HSMSWebService1Soap
     */
    @WebEndpoint(name = "HSMSWebService1Soap12")
    public HSMSWebService1Soap getHSMSWebService1Soap12() {
        return super.getPort(new QName("http://experian.com/bureau/hosted/nbsm", "HSMSWebService1Soap12"), HSMSWebService1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HSMSWebService1Soap
     */
    @WebEndpoint(name = "HSMSWebService1Soap12")
    public HSMSWebService1Soap getHSMSWebService1Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://experian.com/bureau/hosted/nbsm", "HSMSWebService1Soap12"), HSMSWebService1Soap.class, features);
    }

}
