//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.04 at 04:17:01 PM MSK 
//


package ru.simplgroupp.xsd.nbki;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Calculations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Calculations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalAccts" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalZeroBalanceAccounts" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalActiveBalanceAccounts" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="negativeRating" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="paid" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="mostRecentAcc" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="oldest" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="totalHighCredit" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalCurrentBalance" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalPastDueBalance" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalOutstandingBalance" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalScheduledPaymnts" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="installment" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="revolving" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="open" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="mortgage" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalOfficialInfo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalLegalItems" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalBankruptcies" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalLiabilityBalance" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalLegalItemsBalance" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalCollections" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalCollectionsBalance" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalClosedForCauseBalance" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalReturnedItems" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalReturnedItemsBalance" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalClosedForCause" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="mostRecentOfficialInfo" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="mostRecentLegalItem" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="mostRecentBankruptcy" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="mostRecentCollection" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="mostRecentReturnedItem" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="mostRecentClosedForCause" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="totalInquiries" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="recentInquiries" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="collectionsInquiries" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="mostRecentInq" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="mostRecentInqText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creditCard" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dynamicID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dynamicIDType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dynamicCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dynamicCountryCodeText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="primaryId" type="{}Id" minOccurs="0"/>
 *         &lt;element name="reportIssueDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="totalBankingAccts" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalBankingBalance" type="{}CurrencyCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalNegBankingAccts" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="mostRecentBanking" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="oldestBanking" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="accountsGroupTotal" type="{}AccountsGroupTotal" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalDisputedAccounts" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalDisputedBankruptcy" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalDisputedLegalItem" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="totalDisputedOfficialInfo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Calculations", propOrder = {
    "totalAccts",
    "totalZeroBalanceAccounts",
    "totalActiveBalanceAccounts",
    "negativeRating",
    "paid",
    "mostRecentAcc",
    "oldest",
    "totalHighCredit",
    "totalCurrentBalance",
    "totalPastDueBalance",
    "totalOutstandingBalance",
    "totalScheduledPaymnts",
    "installment",
    "revolving",
    "open",
    "mortgage",
    "totalOfficialInfo",
    "totalLegalItems",
    "totalBankruptcies",
    "totalLiabilityBalance",
    "totalLegalItemsBalance",
    "totalCollections",
    "totalCollectionsBalance",
    "totalClosedForCauseBalance",
    "totalReturnedItems",
    "totalReturnedItemsBalance",
    "totalClosedForCause",
    "mostRecentOfficialInfo",
    "mostRecentLegalItem",
    "mostRecentBankruptcy",
    "mostRecentCollection",
    "mostRecentReturnedItem",
    "mostRecentClosedForCause",
    "totalInquiries",
    "recentInquiries",
    "collectionsInquiries",
    "mostRecentInq",
    "mostRecentInqText",
    "creditCard",
    "dynamicID",
    "dynamicIDType",
    "dynamicCountryCode",
    "dynamicCountryCodeText",
    "primaryId",
    "reportIssueDateTime",
    "totalBankingAccts",
    "totalBankingBalance",
    "totalNegBankingAccts",
    "mostRecentBanking",
    "oldestBanking",
    "accountsGroupTotal",
    "totalDisputedAccounts",
    "totalDisputedBankruptcy",
    "totalDisputedLegalItem",
    "totalDisputedOfficialInfo"
})
public class Calculations {

    protected BigInteger totalAccts;
    protected BigInteger totalZeroBalanceAccounts;
    protected BigInteger totalActiveBalanceAccounts;
    protected BigInteger negativeRating;
    protected BigInteger paid;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mostRecentAcc;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar oldest;
    protected List<CurrencyCode> totalHighCredit;
    protected List<CurrencyCode> totalCurrentBalance;
    protected List<CurrencyCode> totalPastDueBalance;
    protected List<CurrencyCode> totalOutstandingBalance;
    protected List<CurrencyCode> totalScheduledPaymnts;
    protected List<CurrencyCode> installment;
    protected List<CurrencyCode> revolving;
    protected List<CurrencyCode> open;
    protected List<CurrencyCode> mortgage;
    protected BigInteger totalOfficialInfo;
    protected BigInteger totalLegalItems;
    protected BigInteger totalBankruptcies;
    protected List<CurrencyCode> totalLiabilityBalance;
    protected List<CurrencyCode> totalLegalItemsBalance;
    protected BigInteger totalCollections;
    protected List<CurrencyCode> totalCollectionsBalance;
    protected List<CurrencyCode> totalClosedForCauseBalance;
    protected BigInteger totalReturnedItems;
    protected List<CurrencyCode> totalReturnedItemsBalance;
    protected BigInteger totalClosedForCause;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mostRecentOfficialInfo;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mostRecentLegalItem;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mostRecentBankruptcy;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mostRecentCollection;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mostRecentReturnedItem;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mostRecentClosedForCause;
    protected BigInteger totalInquiries;
    protected BigInteger recentInquiries;
    protected BigInteger collectionsInquiries;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mostRecentInq;
    protected String mostRecentInqText;
    protected List<CurrencyCode> creditCard;
    protected String dynamicID;
    protected String dynamicIDType;
    protected String dynamicCountryCode;
    protected String dynamicCountryCodeText;
    protected Id primaryId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reportIssueDateTime;
    protected BigInteger totalBankingAccts;
    protected List<CurrencyCode> totalBankingBalance;
    protected BigInteger totalNegBankingAccts;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar mostRecentBanking;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar oldestBanking;
    protected List<AccountsGroupTotal> accountsGroupTotal;
    protected BigInteger totalDisputedAccounts;
    protected BigInteger totalDisputedBankruptcy;
    protected BigInteger totalDisputedLegalItem;
    protected BigInteger totalDisputedOfficialInfo;

    /**
     * Gets the value of the totalAccts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalAccts() {
        return totalAccts;
    }

    /**
     * Sets the value of the totalAccts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalAccts(BigInteger value) {
        this.totalAccts = value;
    }

    /**
     * Gets the value of the totalZeroBalanceAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalZeroBalanceAccounts() {
        return totalZeroBalanceAccounts;
    }

    /**
     * Sets the value of the totalZeroBalanceAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalZeroBalanceAccounts(BigInteger value) {
        this.totalZeroBalanceAccounts = value;
    }

    /**
     * Gets the value of the totalActiveBalanceAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalActiveBalanceAccounts() {
        return totalActiveBalanceAccounts;
    }

    /**
     * Sets the value of the totalActiveBalanceAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalActiveBalanceAccounts(BigInteger value) {
        this.totalActiveBalanceAccounts = value;
    }

    /**
     * Gets the value of the negativeRating property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNegativeRating() {
        return negativeRating;
    }

    /**
     * Sets the value of the negativeRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNegativeRating(BigInteger value) {
        this.negativeRating = value;
    }

    /**
     * Gets the value of the paid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaid() {
        return paid;
    }

    /**
     * Sets the value of the paid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaid(BigInteger value) {
        this.paid = value;
    }

    /**
     * Gets the value of the mostRecentAcc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMostRecentAcc() {
        return mostRecentAcc;
    }

    /**
     * Sets the value of the mostRecentAcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMostRecentAcc(XMLGregorianCalendar value) {
        this.mostRecentAcc = value;
    }

    /**
     * Gets the value of the oldest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOldest() {
        return oldest;
    }

    /**
     * Sets the value of the oldest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOldest(XMLGregorianCalendar value) {
        this.oldest = value;
    }

    /**
     * Gets the value of the totalHighCredit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalHighCredit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalHighCredit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalHighCredit() {
        if (totalHighCredit == null) {
            totalHighCredit = new ArrayList<CurrencyCode>();
        }
        return this.totalHighCredit;
    }

    /**
     * Gets the value of the totalCurrentBalance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalCurrentBalance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalCurrentBalance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalCurrentBalance() {
        if (totalCurrentBalance == null) {
            totalCurrentBalance = new ArrayList<CurrencyCode>();
        }
        return this.totalCurrentBalance;
    }

    /**
     * Gets the value of the totalPastDueBalance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalPastDueBalance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalPastDueBalance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalPastDueBalance() {
        if (totalPastDueBalance == null) {
            totalPastDueBalance = new ArrayList<CurrencyCode>();
        }
        return this.totalPastDueBalance;
    }

    /**
     * Gets the value of the totalOutstandingBalance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalOutstandingBalance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalOutstandingBalance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalOutstandingBalance() {
        if (totalOutstandingBalance == null) {
            totalOutstandingBalance = new ArrayList<CurrencyCode>();
        }
        return this.totalOutstandingBalance;
    }

    /**
     * Gets the value of the totalScheduledPaymnts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalScheduledPaymnts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalScheduledPaymnts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalScheduledPaymnts() {
        if (totalScheduledPaymnts == null) {
            totalScheduledPaymnts = new ArrayList<CurrencyCode>();
        }
        return this.totalScheduledPaymnts;
    }

    /**
     * Gets the value of the installment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the installment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstallment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getInstallment() {
        if (installment == null) {
            installment = new ArrayList<CurrencyCode>();
        }
        return this.installment;
    }

    /**
     * Gets the value of the revolving property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the revolving property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRevolving().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getRevolving() {
        if (revolving == null) {
            revolving = new ArrayList<CurrencyCode>();
        }
        return this.revolving;
    }

    /**
     * Gets the value of the open property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the open property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getOpen() {
        if (open == null) {
            open = new ArrayList<CurrencyCode>();
        }
        return this.open;
    }

    /**
     * Gets the value of the mortgage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mortgage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMortgage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getMortgage() {
        if (mortgage == null) {
            mortgage = new ArrayList<CurrencyCode>();
        }
        return this.mortgage;
    }

    /**
     * Gets the value of the totalOfficialInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalOfficialInfo() {
        return totalOfficialInfo;
    }

    /**
     * Sets the value of the totalOfficialInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalOfficialInfo(BigInteger value) {
        this.totalOfficialInfo = value;
    }

    /**
     * Gets the value of the totalLegalItems property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalLegalItems() {
        return totalLegalItems;
    }

    /**
     * Sets the value of the totalLegalItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalLegalItems(BigInteger value) {
        this.totalLegalItems = value;
    }

    /**
     * Gets the value of the totalBankruptcies property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalBankruptcies() {
        return totalBankruptcies;
    }

    /**
     * Sets the value of the totalBankruptcies property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalBankruptcies(BigInteger value) {
        this.totalBankruptcies = value;
    }

    /**
     * Gets the value of the totalLiabilityBalance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalLiabilityBalance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalLiabilityBalance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalLiabilityBalance() {
        if (totalLiabilityBalance == null) {
            totalLiabilityBalance = new ArrayList<CurrencyCode>();
        }
        return this.totalLiabilityBalance;
    }

    /**
     * Gets the value of the totalLegalItemsBalance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalLegalItemsBalance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalLegalItemsBalance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalLegalItemsBalance() {
        if (totalLegalItemsBalance == null) {
            totalLegalItemsBalance = new ArrayList<CurrencyCode>();
        }
        return this.totalLegalItemsBalance;
    }

    /**
     * Gets the value of the totalCollections property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalCollections() {
        return totalCollections;
    }

    /**
     * Sets the value of the totalCollections property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalCollections(BigInteger value) {
        this.totalCollections = value;
    }

    /**
     * Gets the value of the totalCollectionsBalance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalCollectionsBalance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalCollectionsBalance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalCollectionsBalance() {
        if (totalCollectionsBalance == null) {
            totalCollectionsBalance = new ArrayList<CurrencyCode>();
        }
        return this.totalCollectionsBalance;
    }

    /**
     * Gets the value of the totalClosedForCauseBalance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalClosedForCauseBalance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalClosedForCauseBalance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalClosedForCauseBalance() {
        if (totalClosedForCauseBalance == null) {
            totalClosedForCauseBalance = new ArrayList<CurrencyCode>();
        }
        return this.totalClosedForCauseBalance;
    }

    /**
     * Gets the value of the totalReturnedItems property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalReturnedItems() {
        return totalReturnedItems;
    }

    /**
     * Sets the value of the totalReturnedItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalReturnedItems(BigInteger value) {
        this.totalReturnedItems = value;
    }

    /**
     * Gets the value of the totalReturnedItemsBalance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalReturnedItemsBalance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalReturnedItemsBalance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalReturnedItemsBalance() {
        if (totalReturnedItemsBalance == null) {
            totalReturnedItemsBalance = new ArrayList<CurrencyCode>();
        }
        return this.totalReturnedItemsBalance;
    }

    /**
     * Gets the value of the totalClosedForCause property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalClosedForCause() {
        return totalClosedForCause;
    }

    /**
     * Sets the value of the totalClosedForCause property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalClosedForCause(BigInteger value) {
        this.totalClosedForCause = value;
    }

    /**
     * Gets the value of the mostRecentOfficialInfo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMostRecentOfficialInfo() {
        return mostRecentOfficialInfo;
    }

    /**
     * Sets the value of the mostRecentOfficialInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMostRecentOfficialInfo(XMLGregorianCalendar value) {
        this.mostRecentOfficialInfo = value;
    }

    /**
     * Gets the value of the mostRecentLegalItem property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMostRecentLegalItem() {
        return mostRecentLegalItem;
    }

    /**
     * Sets the value of the mostRecentLegalItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMostRecentLegalItem(XMLGregorianCalendar value) {
        this.mostRecentLegalItem = value;
    }

    /**
     * Gets the value of the mostRecentBankruptcy property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMostRecentBankruptcy() {
        return mostRecentBankruptcy;
    }

    /**
     * Sets the value of the mostRecentBankruptcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMostRecentBankruptcy(XMLGregorianCalendar value) {
        this.mostRecentBankruptcy = value;
    }

    /**
     * Gets the value of the mostRecentCollection property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMostRecentCollection() {
        return mostRecentCollection;
    }

    /**
     * Sets the value of the mostRecentCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMostRecentCollection(XMLGregorianCalendar value) {
        this.mostRecentCollection = value;
    }

    /**
     * Gets the value of the mostRecentReturnedItem property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMostRecentReturnedItem() {
        return mostRecentReturnedItem;
    }

    /**
     * Sets the value of the mostRecentReturnedItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMostRecentReturnedItem(XMLGregorianCalendar value) {
        this.mostRecentReturnedItem = value;
    }

    /**
     * Gets the value of the mostRecentClosedForCause property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMostRecentClosedForCause() {
        return mostRecentClosedForCause;
    }

    /**
     * Sets the value of the mostRecentClosedForCause property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMostRecentClosedForCause(XMLGregorianCalendar value) {
        this.mostRecentClosedForCause = value;
    }

    /**
     * Gets the value of the totalInquiries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalInquiries() {
        return totalInquiries;
    }

    /**
     * Sets the value of the totalInquiries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalInquiries(BigInteger value) {
        this.totalInquiries = value;
    }

    /**
     * Gets the value of the recentInquiries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecentInquiries() {
        return recentInquiries;
    }

    /**
     * Sets the value of the recentInquiries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecentInquiries(BigInteger value) {
        this.recentInquiries = value;
    }

    /**
     * Gets the value of the collectionsInquiries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCollectionsInquiries() {
        return collectionsInquiries;
    }

    /**
     * Sets the value of the collectionsInquiries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCollectionsInquiries(BigInteger value) {
        this.collectionsInquiries = value;
    }

    /**
     * Gets the value of the mostRecentInq property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMostRecentInq() {
        return mostRecentInq;
    }

    /**
     * Sets the value of the mostRecentInq property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMostRecentInq(XMLGregorianCalendar value) {
        this.mostRecentInq = value;
    }

    /**
     * Gets the value of the mostRecentInqText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMostRecentInqText() {
        return mostRecentInqText;
    }

    /**
     * Sets the value of the mostRecentInqText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMostRecentInqText(String value) {
        this.mostRecentInqText = value;
    }

    /**
     * Gets the value of the creditCard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditCard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditCard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getCreditCard() {
        if (creditCard == null) {
            creditCard = new ArrayList<CurrencyCode>();
        }
        return this.creditCard;
    }

    /**
     * Gets the value of the dynamicID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDynamicID() {
        return dynamicID;
    }

    /**
     * Sets the value of the dynamicID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDynamicID(String value) {
        this.dynamicID = value;
    }

    /**
     * Gets the value of the dynamicIDType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDynamicIDType() {
        return dynamicIDType;
    }

    /**
     * Sets the value of the dynamicIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDynamicIDType(String value) {
        this.dynamicIDType = value;
    }

    /**
     * Gets the value of the dynamicCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDynamicCountryCode() {
        return dynamicCountryCode;
    }

    /**
     * Sets the value of the dynamicCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDynamicCountryCode(String value) {
        this.dynamicCountryCode = value;
    }

    /**
     * Gets the value of the dynamicCountryCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDynamicCountryCodeText() {
        return dynamicCountryCodeText;
    }

    /**
     * Sets the value of the dynamicCountryCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDynamicCountryCodeText(String value) {
        this.dynamicCountryCodeText = value;
    }

    /**
     * Gets the value of the primaryId property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getPrimaryId() {
        return primaryId;
    }

    /**
     * Sets the value of the primaryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setPrimaryId(Id value) {
        this.primaryId = value;
    }

    /**
     * Gets the value of the reportIssueDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportIssueDateTime() {
        return reportIssueDateTime;
    }

    /**
     * Sets the value of the reportIssueDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportIssueDateTime(XMLGregorianCalendar value) {
        this.reportIssueDateTime = value;
    }

    /**
     * Gets the value of the totalBankingAccts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalBankingAccts() {
        return totalBankingAccts;
    }

    /**
     * Sets the value of the totalBankingAccts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalBankingAccts(BigInteger value) {
        this.totalBankingAccts = value;
    }

    /**
     * Gets the value of the totalBankingBalance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalBankingBalance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalBankingBalance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyCode }
     * 
     * 
     */
    public List<CurrencyCode> getTotalBankingBalance() {
        if (totalBankingBalance == null) {
            totalBankingBalance = new ArrayList<CurrencyCode>();
        }
        return this.totalBankingBalance;
    }

    /**
     * Gets the value of the totalNegBankingAccts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalNegBankingAccts() {
        return totalNegBankingAccts;
    }

    /**
     * Sets the value of the totalNegBankingAccts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalNegBankingAccts(BigInteger value) {
        this.totalNegBankingAccts = value;
    }

    /**
     * Gets the value of the mostRecentBanking property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMostRecentBanking() {
        return mostRecentBanking;
    }

    /**
     * Sets the value of the mostRecentBanking property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMostRecentBanking(XMLGregorianCalendar value) {
        this.mostRecentBanking = value;
    }

    /**
     * Gets the value of the oldestBanking property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOldestBanking() {
        return oldestBanking;
    }

    /**
     * Sets the value of the oldestBanking property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOldestBanking(XMLGregorianCalendar value) {
        this.oldestBanking = value;
    }

    /**
     * Gets the value of the accountsGroupTotal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountsGroupTotal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountsGroupTotal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountsGroupTotal }
     * 
     * 
     */
    public List<AccountsGroupTotal> getAccountsGroupTotal() {
        if (accountsGroupTotal == null) {
            accountsGroupTotal = new ArrayList<AccountsGroupTotal>();
        }
        return this.accountsGroupTotal;
    }

    /**
     * Gets the value of the totalDisputedAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalDisputedAccounts() {
        return totalDisputedAccounts;
    }

    /**
     * Sets the value of the totalDisputedAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalDisputedAccounts(BigInteger value) {
        this.totalDisputedAccounts = value;
    }

    /**
     * Gets the value of the totalDisputedBankruptcy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalDisputedBankruptcy() {
        return totalDisputedBankruptcy;
    }

    /**
     * Sets the value of the totalDisputedBankruptcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalDisputedBankruptcy(BigInteger value) {
        this.totalDisputedBankruptcy = value;
    }

    /**
     * Gets the value of the totalDisputedLegalItem property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalDisputedLegalItem() {
        return totalDisputedLegalItem;
    }

    /**
     * Sets the value of the totalDisputedLegalItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalDisputedLegalItem(BigInteger value) {
        this.totalDisputedLegalItem = value;
    }

    /**
     * Gets the value of the totalDisputedOfficialInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalDisputedOfficialInfo() {
        return totalDisputedOfficialInfo;
    }

    /**
     * Sets the value of the totalDisputedOfficialInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalDisputedOfficialInfo(BigInteger value) {
        this.totalDisputedOfficialInfo = value;
    }

}
