//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.04 at 04:17:01 PM MSK 
//


package ru.simplgroupp.xsd.nbki;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Collection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Collection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fid" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="serialNum" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="srcCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="srcCountryCodeText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="memberCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="memberTypeText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="memberNameText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="memberContactText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fileSinceDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="acctNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creditor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creditorAcct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="collectionStatusText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportingDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="openedDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="paidDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="curBalance" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="origBalance" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="currencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="narrativeCode1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="narrativeCode2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="narrativeCode1Text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="narrativeCode2Text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastUpdatedDt" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="freezeFlag" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="suppressFlag" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="suppressStrDt" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="suppressEndDt" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Collection", propOrder = {
    "fid",
    "serialNum",
    "srcCountryCode",
    "srcCountryCodeText",
    "memberCode",
    "memberTypeText",
    "memberNameText",
    "memberContactText",
    "fileSinceDt",
    "acctNum",
    "creditor",
    "creditorAcct",
    "status",
    "collectionStatusText",
    "reportingDt",
    "openedDt",
    "paidDt",
    "curBalance",
    "origBalance",
    "currencyCode",
    "narrativeCode1",
    "narrativeCode2",
    "narrativeCode1Text",
    "narrativeCode2Text",
    "lastUpdatedDt",
    "freezeFlag",
    "suppressFlag",
    "suppressStrDt",
    "suppressEndDt"
})
public class Collection {

    protected BigInteger fid;
    protected Long serialNum;
    protected String srcCountryCode;
    protected String srcCountryCodeText;
    protected String memberCode;
    protected String memberTypeText;
    protected String memberNameText;
    protected String memberContactText;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fileSinceDt;
    protected String acctNum;
    protected String creditor;
    protected String creditorAcct;
    protected String status;
    protected String collectionStatusText;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar reportingDt;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar openedDt;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paidDt;
    protected BigInteger curBalance;
    protected BigInteger origBalance;
    protected String currencyCode;
    protected String narrativeCode1;
    protected String narrativeCode2;
    protected String narrativeCode1Text;
    protected String narrativeCode2Text;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastUpdatedDt;
    protected BigInteger freezeFlag;
    protected BigInteger suppressFlag;
    protected BigInteger suppressStrDt;
    protected BigInteger suppressEndDt;

    /**
     * Gets the value of the fid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFid() {
        return fid;
    }

    /**
     * Sets the value of the fid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFid(BigInteger value) {
        this.fid = value;
    }

    /**
     * Gets the value of the serialNum property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSerialNum() {
        return serialNum;
    }

    /**
     * Sets the value of the serialNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSerialNum(Long value) {
        this.serialNum = value;
    }

    /**
     * Gets the value of the srcCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcCountryCode() {
        return srcCountryCode;
    }

    /**
     * Sets the value of the srcCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcCountryCode(String value) {
        this.srcCountryCode = value;
    }

    /**
     * Gets the value of the srcCountryCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcCountryCodeText() {
        return srcCountryCodeText;
    }

    /**
     * Sets the value of the srcCountryCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcCountryCodeText(String value) {
        this.srcCountryCodeText = value;
    }

    /**
     * Gets the value of the memberCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * Sets the value of the memberCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberCode(String value) {
        this.memberCode = value;
    }

    /**
     * Gets the value of the memberTypeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberTypeText() {
        return memberTypeText;
    }

    /**
     * Sets the value of the memberTypeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberTypeText(String value) {
        this.memberTypeText = value;
    }

    /**
     * Gets the value of the memberNameText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberNameText() {
        return memberNameText;
    }

    /**
     * Sets the value of the memberNameText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberNameText(String value) {
        this.memberNameText = value;
    }

    /**
     * Gets the value of the memberContactText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberContactText() {
        return memberContactText;
    }

    /**
     * Sets the value of the memberContactText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberContactText(String value) {
        this.memberContactText = value;
    }

    /**
     * Gets the value of the fileSinceDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFileSinceDt() {
        return fileSinceDt;
    }

    /**
     * Sets the value of the fileSinceDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFileSinceDt(XMLGregorianCalendar value) {
        this.fileSinceDt = value;
    }

    /**
     * Gets the value of the acctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctNum() {
        return acctNum;
    }

    /**
     * Sets the value of the acctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctNum(String value) {
        this.acctNum = value;
    }

    /**
     * Gets the value of the creditor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditor() {
        return creditor;
    }

    /**
     * Sets the value of the creditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditor(String value) {
        this.creditor = value;
    }

    /**
     * Gets the value of the creditorAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditorAcct() {
        return creditorAcct;
    }

    /**
     * Sets the value of the creditorAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditorAcct(String value) {
        this.creditorAcct = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the collectionStatusText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectionStatusText() {
        return collectionStatusText;
    }

    /**
     * Sets the value of the collectionStatusText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionStatusText(String value) {
        this.collectionStatusText = value;
    }

    /**
     * Gets the value of the reportingDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportingDt() {
        return reportingDt;
    }

    /**
     * Sets the value of the reportingDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportingDt(XMLGregorianCalendar value) {
        this.reportingDt = value;
    }

    /**
     * Gets the value of the openedDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOpenedDt() {
        return openedDt;
    }

    /**
     * Sets the value of the openedDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOpenedDt(XMLGregorianCalendar value) {
        this.openedDt = value;
    }

    /**
     * Gets the value of the paidDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaidDt() {
        return paidDt;
    }

    /**
     * Sets the value of the paidDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaidDt(XMLGregorianCalendar value) {
        this.paidDt = value;
    }

    /**
     * Gets the value of the curBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCurBalance() {
        return curBalance;
    }

    /**
     * Sets the value of the curBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCurBalance(BigInteger value) {
        this.curBalance = value;
    }

    /**
     * Gets the value of the origBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrigBalance() {
        return origBalance;
    }

    /**
     * Sets the value of the origBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrigBalance(BigInteger value) {
        this.origBalance = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the narrativeCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNarrativeCode1() {
        return narrativeCode1;
    }

    /**
     * Sets the value of the narrativeCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNarrativeCode1(String value) {
        this.narrativeCode1 = value;
    }

    /**
     * Gets the value of the narrativeCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNarrativeCode2() {
        return narrativeCode2;
    }

    /**
     * Sets the value of the narrativeCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNarrativeCode2(String value) {
        this.narrativeCode2 = value;
    }

    /**
     * Gets the value of the narrativeCode1Text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNarrativeCode1Text() {
        return narrativeCode1Text;
    }

    /**
     * Sets the value of the narrativeCode1Text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNarrativeCode1Text(String value) {
        this.narrativeCode1Text = value;
    }

    /**
     * Gets the value of the narrativeCode2Text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNarrativeCode2Text() {
        return narrativeCode2Text;
    }

    /**
     * Sets the value of the narrativeCode2Text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNarrativeCode2Text(String value) {
        this.narrativeCode2Text = value;
    }

    /**
     * Gets the value of the lastUpdatedDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedDt() {
        return lastUpdatedDt;
    }

    /**
     * Sets the value of the lastUpdatedDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedDt(XMLGregorianCalendar value) {
        this.lastUpdatedDt = value;
    }

    /**
     * Gets the value of the freezeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreezeFlag() {
        return freezeFlag;
    }

    /**
     * Sets the value of the freezeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreezeFlag(BigInteger value) {
        this.freezeFlag = value;
    }

    /**
     * Gets the value of the suppressFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSuppressFlag() {
        return suppressFlag;
    }

    /**
     * Sets the value of the suppressFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSuppressFlag(BigInteger value) {
        this.suppressFlag = value;
    }

    /**
     * Gets the value of the suppressStrDt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSuppressStrDt() {
        return suppressStrDt;
    }

    /**
     * Sets the value of the suppressStrDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSuppressStrDt(BigInteger value) {
        this.suppressStrDt = value;
    }

    /**
     * Gets the value of the suppressEndDt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSuppressEndDt() {
        return suppressEndDt;
    }

    /**
     * Sets the value of the suppressEndDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSuppressEndDt(BigInteger value) {
        this.suppressEndDt = value;
    }

}
