//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.04 at 04:17:01 PM MSK 
//


package ru.simplgroupp.xsd.nbki;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CreditReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubjectReply" type="{}Subject" minOccurs="0"/>
 *         &lt;element name="PersonReply" type="{}Person" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IdReply" type="{}Id" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AddressReply" type="{}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhoneReply" type="{}Phone" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EmploymentReply" type="{}Employment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AccountReply" type="{}Account" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BankingReply" type="{}Banking" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CollectionReply" type="{}Collection" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LegalItemsReply" type="{}LegalItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OfficialInfoReply" type="{}OfficialInformation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BankruptcyReply" type="{}Bankruptcy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ClosedForCauseReply" type="{}ClosedForCause" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReturnedItemReply" type="{}ReturnedItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ConsumerStatementReply" type="{}ConsumerStatement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BusinessReply" type="{}Business" minOccurs="0"/>
 *         &lt;element name="ClassificationReply" type="{}Classification" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InquiryReply" type="{}Inquiry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OwnAccounts" type="{}OwnAccounts" minOccurs="0"/>
 *         &lt;element name="addOns" type="{}addOns" minOccurs="0"/>
 *         &lt;element name="calc" type="{}Calculations" minOccurs="0"/>
 *         &lt;element name="groups" type="{}GroupsType" minOccurs="0"/>
 *         &lt;element name="inqControlNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SuppressionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="memberCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MemberCodeStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="returnCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="replyDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="rawReply" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditReport", propOrder = {
    "subjectReply",
    "personReply",
    "idReply",
    "addressReply",
    "phoneReply",
    "employmentReply",
    "accountReply",
    "bankingReply",
    "collectionReply",
    "legalItemsReply",
    "officialInfoReply",
    "bankruptcyReply",
    "closedForCauseReply",
    "returnedItemReply",
    "consumerStatementReply",
    "businessReply",
    "classificationReply",
    "inquiryReply",
    "ownAccounts",
    "addOns",
    "calc",
    "groups",
    "inqControlNum",
    "suppressionStatus",
    "memberCode",
    "memberCodeStatus",
    "returnCode",
    "replyDateTime",
    "rawReply"
})
public class CreditReport {

    @XmlElement(name = "SubjectReply")
    protected Subject subjectReply;
    @XmlElement(name = "PersonReply")
    protected List<Person> personReply;
    @XmlElement(name = "IdReply")
    protected List<Id> idReply;
    @XmlElement(name = "AddressReply")
    protected List<Address> addressReply;
    @XmlElement(name = "PhoneReply")
    protected List<Phone> phoneReply;
    @XmlElement(name = "EmploymentReply")
    protected List<Employment> employmentReply;
    @XmlElement(name = "AccountReply")
    protected List<Account> accountReply;
    @XmlElement(name = "BankingReply")
    protected List<Banking> bankingReply;
    @XmlElement(name = "CollectionReply")
    protected List<Collection> collectionReply;
    @XmlElement(name = "LegalItemsReply")
    protected List<LegalItem> legalItemsReply;
    @XmlElement(name = "OfficialInfoReply")
    protected List<OfficialInformation> officialInfoReply;
    @XmlElement(name = "BankruptcyReply")
    protected List<Bankruptcy> bankruptcyReply;
    @XmlElement(name = "ClosedForCauseReply")
    protected List<ClosedForCause> closedForCauseReply;
    @XmlElement(name = "ReturnedItemReply")
    protected List<ReturnedItem> returnedItemReply;
    @XmlElement(name = "ConsumerStatementReply")
    protected List<ConsumerStatement> consumerStatementReply;
    @XmlElement(name = "BusinessReply")
    protected Business businessReply;
    @XmlElement(name = "ClassificationReply")
    protected List<Classification> classificationReply;
    @XmlElement(name = "InquiryReply")
    protected List<Inquiry> inquiryReply;
    @XmlElement(name = "OwnAccounts")
    protected OwnAccounts ownAccounts;
    protected AddOns addOns;
    protected Calculations calc;
    protected GroupsType groups;
    protected String inqControlNum;
    @XmlElement(name = "SuppressionStatus")
    protected String suppressionStatus;
    protected String memberCode;
    @XmlElement(name = "MemberCodeStatus")
    protected String memberCodeStatus;
    protected String returnCode;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar replyDateTime;
    protected String rawReply;

    /**
     * Gets the value of the subjectReply property.
     * 
     * @return
     *     possible object is
     *     {@link Subject }
     *     
     */
    public Subject getSubjectReply() {
        return subjectReply;
    }

    /**
     * Sets the value of the subjectReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subject }
     *     
     */
    public void setSubjectReply(Subject value) {
        this.subjectReply = value;
    }

    /**
     * Gets the value of the personReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Person }
     * 
     * 
     */
    public List<Person> getPersonReply() {
        if (personReply == null) {
            personReply = new ArrayList<Person>();
        }
        return this.personReply;
    }

    /**
     * Gets the value of the idReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Id }
     * 
     * 
     */
    public List<Id> getIdReply() {
        if (idReply == null) {
            idReply = new ArrayList<Id>();
        }
        return this.idReply;
    }

    /**
     * Gets the value of the addressReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddressReply() {
        if (addressReply == null) {
            addressReply = new ArrayList<Address>();
        }
        return this.addressReply;
    }

    /**
     * Gets the value of the phoneReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phoneReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhoneReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Phone }
     * 
     * 
     */
    public List<Phone> getPhoneReply() {
        if (phoneReply == null) {
            phoneReply = new ArrayList<Phone>();
        }
        return this.phoneReply;
    }

    /**
     * Gets the value of the employmentReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the employmentReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmploymentReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Employment }
     * 
     * 
     */
    public List<Employment> getEmploymentReply() {
        if (employmentReply == null) {
            employmentReply = new ArrayList<Employment>();
        }
        return this.employmentReply;
    }

    /**
     * Gets the value of the accountReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Account }
     * 
     * 
     */
    public List<Account> getAccountReply() {
        if (accountReply == null) {
            accountReply = new ArrayList<Account>();
        }
        return this.accountReply;
    }

    /**
     * Gets the value of the bankingReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankingReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankingReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Banking }
     * 
     * 
     */
    public List<Banking> getBankingReply() {
        if (bankingReply == null) {
            bankingReply = new ArrayList<Banking>();
        }
        return this.bankingReply;
    }

    /**
     * Gets the value of the collectionReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the collectionReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCollectionReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Collection }
     * 
     * 
     */
    public List<Collection> getCollectionReply() {
        if (collectionReply == null) {
            collectionReply = new ArrayList<Collection>();
        }
        return this.collectionReply;
    }

    /**
     * Gets the value of the legalItemsReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legalItemsReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegalItemsReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LegalItem }
     * 
     * 
     */
    public List<LegalItem> getLegalItemsReply() {
        if (legalItemsReply == null) {
            legalItemsReply = new ArrayList<LegalItem>();
        }
        return this.legalItemsReply;
    }

    /**
     * Gets the value of the officialInfoReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the officialInfoReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOfficialInfoReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OfficialInformation }
     * 
     * 
     */
    public List<OfficialInformation> getOfficialInfoReply() {
        if (officialInfoReply == null) {
            officialInfoReply = new ArrayList<OfficialInformation>();
        }
        return this.officialInfoReply;
    }

    /**
     * Gets the value of the bankruptcyReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankruptcyReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankruptcyReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bankruptcy }
     * 
     * 
     */
    public List<Bankruptcy> getBankruptcyReply() {
        if (bankruptcyReply == null) {
            bankruptcyReply = new ArrayList<Bankruptcy>();
        }
        return this.bankruptcyReply;
    }

    /**
     * Gets the value of the closedForCauseReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the closedForCauseReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClosedForCauseReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClosedForCause }
     * 
     * 
     */
    public List<ClosedForCause> getClosedForCauseReply() {
        if (closedForCauseReply == null) {
            closedForCauseReply = new ArrayList<ClosedForCause>();
        }
        return this.closedForCauseReply;
    }

    /**
     * Gets the value of the returnedItemReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnedItemReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturnedItemReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReturnedItem }
     * 
     * 
     */
    public List<ReturnedItem> getReturnedItemReply() {
        if (returnedItemReply == null) {
            returnedItemReply = new ArrayList<ReturnedItem>();
        }
        return this.returnedItemReply;
    }

    /**
     * Gets the value of the consumerStatementReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the consumerStatementReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConsumerStatementReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConsumerStatement }
     * 
     * 
     */
    public List<ConsumerStatement> getConsumerStatementReply() {
        if (consumerStatementReply == null) {
            consumerStatementReply = new ArrayList<ConsumerStatement>();
        }
        return this.consumerStatementReply;
    }

    /**
     * Gets the value of the businessReply property.
     * 
     * @return
     *     possible object is
     *     {@link Business }
     *     
     */
    public Business getBusinessReply() {
        return businessReply;
    }

    /**
     * Sets the value of the businessReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Business }
     *     
     */
    public void setBusinessReply(Business value) {
        this.businessReply = value;
    }

    /**
     * Gets the value of the classificationReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classificationReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassificationReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Classification }
     * 
     * 
     */
    public List<Classification> getClassificationReply() {
        if (classificationReply == null) {
            classificationReply = new ArrayList<Classification>();
        }
        return this.classificationReply;
    }

    /**
     * Gets the value of the inquiryReply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inquiryReply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInquiryReply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Inquiry }
     * 
     * 
     */
    public List<Inquiry> getInquiryReply() {
        if (inquiryReply == null) {
            inquiryReply = new ArrayList<Inquiry>();
        }
        return this.inquiryReply;
    }

    /**
     * Gets the value of the ownAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link OwnAccounts }
     *     
     */
    public OwnAccounts getOwnAccounts() {
        return ownAccounts;
    }

    /**
     * Sets the value of the ownAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnAccounts }
     *     
     */
    public void setOwnAccounts(OwnAccounts value) {
        this.ownAccounts = value;
    }

    /**
     * Gets the value of the addOns property.
     * 
     * @return
     *     possible object is
     *     {@link AddOns }
     *     
     */
    public AddOns getAddOns() {
        return addOns;
    }

    /**
     * Sets the value of the addOns property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddOns }
     *     
     */
    public void setAddOns(AddOns value) {
        this.addOns = value;
    }

    /**
     * Gets the value of the calc property.
     * 
     * @return
     *     possible object is
     *     {@link Calculations }
     *     
     */
    public Calculations getCalc() {
        return calc;
    }

    /**
     * Sets the value of the calc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calculations }
     *     
     */
    public void setCalc(Calculations value) {
        this.calc = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link GroupsType }
     *     
     */
    public GroupsType getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupsType }
     *     
     */
    public void setGroups(GroupsType value) {
        this.groups = value;
    }

    /**
     * Gets the value of the inqControlNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInqControlNum() {
        return inqControlNum;
    }

    /**
     * Sets the value of the inqControlNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInqControlNum(String value) {
        this.inqControlNum = value;
    }

    /**
     * Gets the value of the suppressionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressionStatus() {
        return suppressionStatus;
    }

    /**
     * Sets the value of the suppressionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressionStatus(String value) {
        this.suppressionStatus = value;
    }

    /**
     * Gets the value of the memberCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * Sets the value of the memberCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberCode(String value) {
        this.memberCode = value;
    }

    /**
     * Gets the value of the memberCodeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberCodeStatus() {
        return memberCodeStatus;
    }

    /**
     * Sets the value of the memberCodeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberCodeStatus(String value) {
        this.memberCodeStatus = value;
    }

    /**
     * Gets the value of the returnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * Sets the value of the returnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnCode(String value) {
        this.returnCode = value;
    }

    /**
     * Gets the value of the replyDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReplyDateTime() {
        return replyDateTime;
    }

    /**
     * Sets the value of the replyDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReplyDateTime(XMLGregorianCalendar value) {
        this.replyDateTime = value;
    }

    /**
     * Gets the value of the rawReply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRawReply() {
        return rawReply;
    }

    /**
     * Sets the value of the rawReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRawReply(String value) {
        this.rawReply = value;
    }

}
