//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.04 at 04:17:01 PM MSK 
//


package ru.simplgroupp.xsd.nbki;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CreditReportRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditReportRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountReq" type="{}Account" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AddressReq" type="{}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EmploymentReq" type="{}Employment" minOccurs="0"/>
 *         &lt;element name="IdReq" type="{}Id" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InquiryReq" type="{}Inquiry" minOccurs="0"/>
 *         &lt;element name="PersonReq" type="{}Person" minOccurs="0"/>
 *         &lt;element name="BusinessReq" type="{}Business" minOccurs="0"/>
 *         &lt;element name="ClassificationReq" type="{}Classification" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhoneReq" type="{}Phone" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="alertReq" type="{}AlertMessage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RequestorReq" type="{}Requestor" minOccurs="0"/>
 *         &lt;element name="RefReq" type="{}Reference" minOccurs="0"/>
 *         &lt;element name="BrokerReq" type="{}Broker" minOccurs="0"/>
 *         &lt;element name="requestDateTime" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="IOType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OutputFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditReportRequest", propOrder = {
    "accountReq",
    "addressReq",
    "employmentReq",
    "idReq",
    "inquiryReq",
    "personReq",
    "businessReq",
    "classificationReq",
    "phoneReq",
    "alertReq",
    "requestorReq",
    "refReq",
    "brokerReq",
    "requestDateTime",
    "ioType",
    "outputFormat",
    "password",
    "lang"
})
public class CreditReportRequest {

    @XmlElement(name = "AccountReq")
    protected List<Account> accountReq;
    @XmlElement(name = "AddressReq")
    protected List<Address> addressReq;
    @XmlElement(name = "EmploymentReq")
    protected Employment employmentReq;
    @XmlElement(name = "IdReq")
    protected List<Id> idReq;
    @XmlElement(name = "InquiryReq")
    protected Inquiry inquiryReq;
    @XmlElement(name = "PersonReq")
    protected Person personReq;
    @XmlElement(name = "BusinessReq")
    protected Business businessReq;
    @XmlElement(name = "ClassificationReq")
    protected List<Classification> classificationReq;
    @XmlElement(name = "PhoneReq")
    protected List<Phone> phoneReq;
    protected List<AlertMessage> alertReq;
    @XmlElement(name = "RequestorReq")
    protected Requestor requestorReq;
    @XmlElement(name = "RefReq")
    protected Reference refReq;
    @XmlElement(name = "BrokerReq")
    protected Broker brokerReq;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar requestDateTime;
    @XmlElement(name = "IOType")
    protected String ioType;
    @XmlElement(name = "OutputFormat")
    protected String outputFormat;
    @XmlElement(name = "Password")
    protected String password;
    protected String lang;

    /**
     * Gets the value of the accountReq property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountReq property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountReq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Account }
     * 
     * 
     */
    public List<Account> getAccountReq() {
        if (accountReq == null) {
            accountReq = new ArrayList<Account>();
        }
        return this.accountReq;
    }

    /**
     * Gets the value of the addressReq property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressReq property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressReq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddressReq() {
        if (addressReq == null) {
            addressReq = new ArrayList<Address>();
        }
        return this.addressReq;
    }

    /**
     * Gets the value of the employmentReq property.
     * 
     * @return
     *     possible object is
     *     {@link Employment }
     *     
     */
    public Employment getEmploymentReq() {
        return employmentReq;
    }

    /**
     * Sets the value of the employmentReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employment }
     *     
     */
    public void setEmploymentReq(Employment value) {
        this.employmentReq = value;
    }

    /**
     * Gets the value of the idReq property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idReq property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdReq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Id }
     * 
     * 
     */
    public List<Id> getIdReq() {
        if (idReq == null) {
            idReq = new ArrayList<Id>();
        }
        return this.idReq;
    }

    /**
     * Gets the value of the inquiryReq property.
     * 
     * @return
     *     possible object is
     *     {@link Inquiry }
     *     
     */
    public Inquiry getInquiryReq() {
        return inquiryReq;
    }

    /**
     * Sets the value of the inquiryReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inquiry }
     *     
     */
    public void setInquiryReq(Inquiry value) {
        this.inquiryReq = value;
    }

    /**
     * Gets the value of the personReq property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPersonReq() {
        return personReq;
    }

    /**
     * Sets the value of the personReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPersonReq(Person value) {
        this.personReq = value;
    }

    /**
     * Gets the value of the businessReq property.
     * 
     * @return
     *     possible object is
     *     {@link Business }
     *     
     */
    public Business getBusinessReq() {
        return businessReq;
    }

    /**
     * Sets the value of the businessReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Business }
     *     
     */
    public void setBusinessReq(Business value) {
        this.businessReq = value;
    }

    /**
     * Gets the value of the classificationReq property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classificationReq property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassificationReq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Classification }
     * 
     * 
     */
    public List<Classification> getClassificationReq() {
        if (classificationReq == null) {
            classificationReq = new ArrayList<Classification>();
        }
        return this.classificationReq;
    }

    /**
     * Gets the value of the phoneReq property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phoneReq property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhoneReq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Phone }
     * 
     * 
     */
    public List<Phone> getPhoneReq() {
        if (phoneReq == null) {
            phoneReq = new ArrayList<Phone>();
        }
        return this.phoneReq;
    }

    /**
     * Gets the value of the alertReq property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alertReq property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlertReq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlertMessage }
     * 
     * 
     */
    public List<AlertMessage> getAlertReq() {
        if (alertReq == null) {
            alertReq = new ArrayList<AlertMessage>();
        }
        return this.alertReq;
    }

    /**
     * Gets the value of the requestorReq property.
     * 
     * @return
     *     possible object is
     *     {@link Requestor }
     *     
     */
    public Requestor getRequestorReq() {
        return requestorReq;
    }

    /**
     * Sets the value of the requestorReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Requestor }
     *     
     */
    public void setRequestorReq(Requestor value) {
        this.requestorReq = value;
    }

    /**
     * Gets the value of the refReq property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getRefReq() {
        return refReq;
    }

    /**
     * Sets the value of the refReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setRefReq(Reference value) {
        this.refReq = value;
    }

    /**
     * Gets the value of the brokerReq property.
     * 
     * @return
     *     possible object is
     *     {@link Broker }
     *     
     */
    public Broker getBrokerReq() {
        return brokerReq;
    }

    /**
     * Sets the value of the brokerReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Broker }
     *     
     */
    public void setBrokerReq(Broker value) {
        this.brokerReq = value;
    }

    /**
     * Gets the value of the requestDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestDateTime() {
        return requestDateTime;
    }

    /**
     * Sets the value of the requestDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestDateTime(XMLGregorianCalendar value) {
        this.requestDateTime = value;
    }

    /**
     * Gets the value of the ioType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIOType() {
        return ioType;
    }

    /**
     * Sets the value of the ioType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIOType(String value) {
        this.ioType = value;
    }

    /**
     * Gets the value of the outputFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputFormat() {
        return outputFormat;
    }

    /**
     * Sets the value of the outputFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputFormat(String value) {
        this.outputFormat = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
