//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.16 at 09:57:53 PM NOVT 
//


package ru.simplgroupp.xsd.nbki;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FicoRiskType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FicoRiskType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="errorText" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="exclusionCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="scoreID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="reasonCode1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reasonCode2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reasonCode3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reasonCode4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="derogIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="systemDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FicoRiskType", propOrder = {
    "uniqueId",
    "errorCode",
    "errorText",
    "exclusionCode",
    "scoreID",
    "score",
    "reasonCode1",
    "reasonCode2",
    "reasonCode3",
    "reasonCode4",
    "derogIndicator",
    "systemDateTime"
})
public class FicoRiskType {

    @XmlElement(required = true)
    protected String uniqueId;
    @XmlElement(required = true)
    protected BigInteger errorCode;
    protected String errorText;
    @XmlElement(required = true)
    protected BigInteger exclusionCode;
    @XmlElement(required = true)
    protected String scoreID;
    @XmlElement(required = true)
    protected BigInteger score;
    @XmlElement(required = true)
    protected String reasonCode1;
    @XmlElement(required = true)
    protected String reasonCode2;
    @XmlElement(required = true)
    protected String reasonCode3;
    @XmlElement(required = true)
    protected String reasonCode4;
    @XmlElement(required = true)
    protected String derogIndicator;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar systemDateTime;

    /**
     * Gets the value of the uniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * Sets the value of the uniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueId(String value) {
        this.uniqueId = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setErrorCode(BigInteger value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the errorText property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getErrorText() {
        return errorText;
    }

    /**
     * Sets the value of the errorText property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setErrorText(String value) {
        this.errorText = value;
    }

    /**
     * Gets the value of the exclusionCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExclusionCode() {
        return exclusionCode;
    }

    /**
     * Sets the value of the exclusionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExclusionCode(BigInteger value) {
        this.exclusionCode = value;
    }

    /**
     * Gets the value of the scoreID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoreID() {
        return scoreID;
    }

    /**
     * Sets the value of the scoreID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoreID(String value) {
        this.scoreID = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScore(BigInteger value) {
        this.score = value;
    }

    /**
     * Gets the value of the reasonCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode1() {
        return reasonCode1;
    }

    /**
     * Sets the value of the reasonCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode1(String value) {
        this.reasonCode1 = value;
    }

    /**
     * Gets the value of the reasonCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode2() {
        return reasonCode2;
    }

    /**
     * Sets the value of the reasonCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode2(String value) {
        this.reasonCode2 = value;
    }

    /**
     * Gets the value of the reasonCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode3() {
        return reasonCode3;
    }

    /**
     * Sets the value of the reasonCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode3(String value) {
        this.reasonCode3 = value;
    }

    /**
     * Gets the value of the reasonCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode4() {
        return reasonCode4;
    }

    /**
     * Sets the value of the reasonCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode4(String value) {
        this.reasonCode4 = value;
    }

    /**
     * Gets the value of the derogIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDerogIndicator() {
        return derogIndicator;
    }

    /**
     * Sets the value of the derogIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDerogIndicator(String value) {
        this.derogIndicator = value;
    }

    /**
     * Gets the value of the systemDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSystemDateTime() {
        return systemDateTime;
    }

    /**
     * Sets the value of the systemDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSystemDateTime(XMLGregorianCalendar value) {
        this.systemDateTime = value;
    }

}
