//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.04 at 04:17:01 PM MSK 
//


package ru.simplgroupp.xsd.nbki;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="report" type="{}CreditReport" minOccurs="0"/>
 *         &lt;element name="log" type="{}CreditReportLog" minOccurs="0"/>
 *         &lt;element name="err" type="{}Error" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductReply", propOrder = {
    "report",
    "log",
    "err"
})
public class ProductReply {

    protected CreditReport report;
    protected CreditReportLog log;
    protected Error err;

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link CreditReport }
     *     
     */
    public CreditReport getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditReport }
     *     
     */
    public void setReport(CreditReport value) {
        this.report = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link CreditReportLog }
     *     
     */
    public CreditReportLog getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditReportLog }
     *     
     */
    public void setLog(CreditReportLog value) {
        this.log = value;
    }

    /**
     * Gets the value of the err property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getErr() {
        return err;
    }

    /**
     * Sets the value of the err property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setErr(Error value) {
        this.err = value;
    }

}
