//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 02:08:54 PM MSK 
//


package ru.simplgroupp.odins.model.rastorop_v2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.rastorop.onlinecreditexchange package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.rastorop.onlinecreditexchange
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdditionalDocument }
     * 
     */
    public AdditionalDocument createAdditionalDocument() {
        return new AdditionalDocument();
    }

    /**
     * Create an instance of {@link Bank }
     * 
     */
    public Bank createBank() {
        return new Bank();
    }

    /**
     * Create an instance of {@link BankAccount }
     * 
     */
    public BankAccount createBankAccount() {
        return new BankAccount();
    }

    /**
     * Create an instance of {@link Companies }
     * 
     */
    public Companies createCompanies() {
        return new Companies();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link Contract }
     * 
     */
    public Contract createContract() {
        return new Contract();
    }

    /**
     * Create an instance of {@link OnlineCreditExchange }
     * 
     */
    public OnlineCreditExchange createOnlineCreditExchange() {
        return new OnlineCreditExchange();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link PaymentExpense }
     * 
     */
    public PaymentExpense createPaymentExpense() {
        return new PaymentExpense();
    }

    /**
     * Create an instance of {@link PaymentReceipt }
     * 
     */
    public PaymentReceipt createPaymentReceipt() {
        return new PaymentReceipt();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link PlaceOfWork }
     * 
     */
    public PlaceOfWork createPlaceOfWork() {
        return new PlaceOfWork();
    }

    /**
     * Create an instance of {@link Relative }
     * 
     */
    public Relative createRelative() {
        return new Relative();
    }

    /**
     * Create an instance of {@link TotalsRecord }
     * 
     */
    public TotalsRecord createTotalsRecord() {
        return new TotalsRecord();
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

}
