//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.08 at 02:08:54 PM MSK 
//


package ru.simplgroupp.odins.model.rastorop_v2;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Person"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="Patronymic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Sex" type="{urn:rastorop.ru:OnlineCreditExchange}Sex"/&gt;
 *         &lt;element name="PassportSeries" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PassportNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PassportIssued" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PassportIssueDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="PlaceOfBirth" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MaritalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AmountOfChildren" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="AmountOfChildrenMinors" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="BankAccount" type="{urn:rastorop.ru:OnlineCreditExchange}BankAccount" minOccurs="0"/&gt;
 *         &lt;element name="ContactInformation" type="{urn:rastorop.ru:OnlineCreditExchange}ContactInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PlacesOfWork" type="{urn:rastorop.ru:OnlineCreditExchange}PlaceOfWork" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Relatives" type="{urn:rastorop.ru:OnlineCreditExchange}Relative" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalDocuments" type="{urn:rastorop.ru:OnlineCreditExchange}AdditionalDocument" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Person", propOrder = {
    "id",
    "name",
    "surname",
    "patronymic",
    "birthDate",
    "sex",
    "passportSeries",
    "passportNumber",
    "passportIssued",
    "passportIssueDate",
    "placeOfBirth",
    "maritalStatus",
    "amountOfChildren",
    "amountOfChildrenMinors",
    "bankAccount",
    "contactInformation",
    "placesOfWork",
    "relatives",
    "additionalDocuments"
})
public class Person {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Surname", required = true)
    protected Object surname;
    @XmlElement(name = "Patronymic", required = true)
    protected String patronymic;
    @XmlElement(name = "BirthDate", required = true)
    @XmlSchemaType(name = "date")
    protected String birthDate;
    @XmlElement(name = "Sex", required = true)
    @XmlSchemaType(name = "string")
    protected Sex sex;
    @XmlElement(name = "PassportSeries", required = true)
    protected String passportSeries;
    @XmlElement(name = "PassportNumber", required = true)
    protected String passportNumber;
    @XmlElement(name = "PassportIssued", required = true)
    protected String passportIssued;
    @XmlElement(name = "PassportIssueDate", required = true)
    @XmlSchemaType(name = "date")
    protected String passportIssueDate;
    @XmlElement(name = "PlaceOfBirth", required = true)
    protected String placeOfBirth;
    @XmlElement(name = "MaritalStatus", required = true)
    protected String maritalStatus;
    @XmlElement(name = "AmountOfChildren", required = true)
    protected String amountOfChildren;
    @XmlElement(name = "AmountOfChildrenMinors", required = true)
    protected String amountOfChildrenMinors;
    @XmlElement(name = "BankAccount")
    protected BankAccount bankAccount;
    @XmlElement(name = "ContactInformation")
    protected List<ContactInformation> contactInformation;
    @XmlElement(name = "PlacesOfWork")
    protected List<PlaceOfWork> placesOfWork;
    @XmlElement(name = "Relatives")
    protected List<Relative> relatives;
    @XmlElement(name = "AdditionalDocuments")
    protected List<AdditionalDocument> additionalDocuments;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSurname(Object value) {
        this.surname = value;
    }

    /**
     * Gets the value of the patronymic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatronymic() {
        return patronymic;
    }

    /**
     * Sets the value of the patronymic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatronymic(String value) {
        this.patronymic = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link Sex }
     *     
     */
    public Sex getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sex }
     *     
     */
    public void setSex(Sex value) {
        this.sex = value;
    }

    /**
     * Gets the value of the passportSeries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportSeries() {
        return passportSeries;
    }

    /**
     * Sets the value of the passportSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportSeries(String value) {
        this.passportSeries = value;
    }

    /**
     * Gets the value of the passportNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportNumber() {
        return passportNumber;
    }

    /**
     * Sets the value of the passportNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportNumber(String value) {
        this.passportNumber = value;
    }

    /**
     * Gets the value of the passportIssued property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportIssued() {
        return passportIssued;
    }

    /**
     * Sets the value of the passportIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportIssued(String value) {
        this.passportIssued = value;
    }

    /**
     * Gets the value of the passportIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportIssueDate() {
        return passportIssueDate;
    }

    /**
     * Sets the value of the passportIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportIssueDate(String value) {
        this.passportIssueDate = value;
    }

    /**
     * Gets the value of the placeOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * Sets the value of the placeOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfBirth(String value) {
        this.placeOfBirth = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the amountOfChildren property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmountOfChildren() {
        return amountOfChildren;
    }

    /**
     * Sets the value of the amountOfChildren property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmountOfChildren(String value) {
        this.amountOfChildren = value;
    }

    /**
     * Gets the value of the amountOfChildrenMinors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmountOfChildrenMinors() {
        return amountOfChildrenMinors;
    }

    /**
     * Sets the value of the amountOfChildrenMinors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmountOfChildrenMinors(String value) {
        this.amountOfChildrenMinors = value;
    }

    /**
     * Gets the value of the bankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link BankAccount }
     *     
     */
    public BankAccount getBankAccount() {
        return bankAccount;
    }

    /**
     * Sets the value of the bankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankAccount }
     *     
     */
    public void setBankAccount(BankAccount value) {
        this.bankAccount = value;
    }

    /**
     * Gets the value of the contactInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactInformation }
     * 
     * 
     */
    public List<ContactInformation> getContactInformation() {
        if (contactInformation == null) {
            contactInformation = new ArrayList<ContactInformation>();
        }
        return this.contactInformation;
    }

    /**
     * Gets the value of the placesOfWork property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the placesOfWork property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlacesOfWork().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlaceOfWork }
     * 
     * 
     */
    public List<PlaceOfWork> getPlacesOfWork() {
        if (placesOfWork == null) {
            placesOfWork = new ArrayList<PlaceOfWork>();
        }
        return this.placesOfWork;
    }

    /**
     * Gets the value of the relatives property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatives property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatives().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Relative }
     * 
     * 
     */
    public List<Relative> getRelatives() {
        if (relatives == null) {
            relatives = new ArrayList<Relative>();
        }
        return this.relatives;
    }

    /**
     * Gets the value of the additionalDocuments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalDocuments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalDocuments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalDocument }
     * 
     * 
     */
    public List<AdditionalDocument> getAdditionalDocuments() {
        if (additionalDocuments == null) {
            additionalDocuments = new ArrayList<AdditionalDocument>();
        }
        return this.additionalDocuments;
    }

}
