import ru.simplgroupp.rules.BooleanRuleResult
import java.util.Map
import ru.simplgroupp.workflow.WorkflowObjectActionDef
import ru.simplgroupp.transfer.Collector
import ru.simplgroupp.util.CollectorKeys
import ru.simplgroupp.util.ProductKeys
import ru.simplgroupp.util.DatesUtils
import java.util.Date
import ru.simplgroupp.rules.AbstractContext

rule "[$RULE_NAME_PREFIX$].1"
when
    $bResult : BooleanRuleResult();
    $actionDef : WorkflowObjectActionDef(businessObjectClass == "ru.simplgroupp.transfer.Collector" && signalRef == "msgToExternalCollector");
    $context : AbstractContext();
    $cparams: Map();
then
	$bResult.setResultValue(false);
	Integer enabled = (Integer) $cparams.get(ProductKeys.COLLECTOR_AGENCY_ENABLED);
	if (enabled == 1) {
		Date dateStart = $context.getCollector().getDatabeg();
		Integer daysAgency = (Integer) $cparams.get(ProductKeys.COLLECTOR_DAYS_AGENCY);

		Integer daysDiff = DatesUtils.daysDiff(new Date(), dateStart);
		if (daysDiff >= daysAgency) {
			$bResult.setResultValue(true);
		}
	}
end