//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.10 at 05:59:42 PM GMT+03:00 
//


package ru.simplgroupp.odins.model.rastorop;

import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Agent", propOrder = {
	"id",	
    "name",
    "inn",
    "kpp"
})
public class Agent {

	@XmlElement(name = "Id", required = true)
	protected String id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Inn", required = true)
    protected String inn;
    @XmlElement(name = "Kpp", required = true)
    protected String kpp;


    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getInn() {
        return inn;
    }

    public void setInn(String inn) {
        this.inn = inn;
    }

    public String getKpp() {
        return kpp;
    }

    public void setKpp(String kpp) {
        this.kpp = kpp;
    }
}
