//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.10 at 05:59:42 PM GMT+03:00 
//


package ru.simplgroupp.odins.model.rastorop;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PaymentReceipt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentReceipt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Num" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Payer" type="{urn:rastorop.ru:OnlineCreditExchange}Person"/>
 *         &lt;element name="Payee" type="{urn:rastorop.ru:OnlineCreditExchange}Organization"/>
 *         &lt;element name="Contract" type="{urn:rastorop.ru:OnlineCreditExchange}Contract"/>
 *         &lt;element name="SumOfInterest" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="SumOfDebt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Overdue" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentReceipt", propOrder = {
    "date",
    "num",
    "payer",
    "payee",
    "contract",
    "sumOfInterest",
    "sumOfDebt",
    "overdue",
    "agent",
    "sum"
})
public class PaymentReceipt {

    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected String date;
    @XmlElement(name = "Num", required = true)
    protected String num;
    @XmlElement(name = "Payer", required = true)
    protected Person payer;
    @XmlElement(name = "Payee", required = true)
    protected Organization payee;
    @XmlElement(name = "Contract", required = true)
    protected Contract contract;
    @XmlElement(name = "SumOfInterest", required = true)
    protected String sumOfInterest;
    @XmlElement(name = "SumOfDebt", required = true)
    protected String sumOfDebt;
    @XmlElement(name = "Overdue")
    protected boolean overdue;
    @XmlElement(name = "Sum", required = true)
    protected String sum;
    @XmlElement(name = "Agent", required = true)
    protected Agent agent;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the num property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNum() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNum(String value) {
        this.num = value;
    }

    /**
     * Gets the value of the payer property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPayer() {
        return payer;
    }

    /**
     * Sets the value of the payer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPayer(Person value) {
        this.payer = value;
    }

    /**
     * Gets the value of the payee property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getPayee() {
        return payee;
    }

    /**
     * Sets the value of the payee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setPayee(Organization value) {
        this.payee = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link Contract }
     *     
     */
    public Contract getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contract }
     *     
     */
    public void setContract(Contract value) {
        this.contract = value;
    }

    /**
     * Gets the value of the sumOfInterest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSumOfInterest() {
        return sumOfInterest;
    }

    /**
     * Sets the value of the sumOfInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSumOfInterest(String value) {
        this.sumOfInterest = value;
    }

    /**
     * Gets the value of the sumOfDebt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSumOfDebt() {
        return sumOfDebt;
    }

    /**
     * Sets the value of the sumOfDebt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSumOfDebt(String value) {
        this.sumOfDebt = value;
    }

    /**
     * Gets the value of the overdue property.
     * 
     */
    public boolean isOverdue() {
        return overdue;
    }

    /**
     * Sets the value of the overdue property.
     * 
     */
    public void setOverdue(boolean value) {
        this.overdue = value;
    }

    public String getSum() {
        return sum;
    }

    public void setSum(String sum) {
        this.sum = sum;
    }

    public Agent getAgent() {
        return agent;
    }

    public void setAgent(Agent agent) {
        this.agent = agent;
    }
}
